server:
  port: DYNAMICPORT
  address: 0.0.0.0
lavalink:
  server:
    password: "iq898989"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: false
      vimeo: false
      http: true
      local: false
    bufferDurationMs: 10000
    frameBufferDurationMs: 10000
    youtubePlaylistLoadLimit: 1
    playerUpdateInterval: 30
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: false
    gc-warnings: true
    ratelimit:
      strategy: "LoadBalance"
      retryLimit: 3

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    max-history: 0
    max-size: 0KB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
