server:
  port: REPLACEPORT
  address: 0.0.0.0
lavalink:
  server:
    password: REPLACEPASSWORD
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: false
      vimeo: false
      http: true
      local: false
    bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses
    frameBufferDurationMs: 4000 # How many milliseconds of audio to keep buffered
    youtubePlaylistLoadLimit: 1
    playerUpdateInterval: 60
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: false
    gc-warnings: true
    ratelimit:
      retryLimit: 3

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    max-history: 0
    max-size: 0KB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
